export const STEAM_TAGS = [
  "Casual",
  "Simulation",
  "Action",
  "Adventure",
  "Racing",
  "RPG",
  "Software",
  "Sports",
  "Strategy",
  "Life Sim",
  "2D Fighter",
  "3D Fighter",
  "4X",
  "Action Roguelike",
  "Action RPG",
  "Action-Adventure",
  "Animation & Modeling",
  "Arcade",
  "Audio Production",
  "Auto Battler",
  "Automobile Sim",
  "Battle Royale",
  "Beat 'em up",
  "Board Game",
  "Card Game",
  "City Builder",
  "Colony Sim",
  "Dating Sim",
  "Design & Illustration",
  "Education",
  "eSports",
  "Farming Sim",
  "God Game",
  "Grand Strategy",
  "Interactive Fiction",
  "JRPG",
  "MMORPG",
  "MOBA",
  "Party Game",
  "Party-Based RPG",
  "Photo Editing",
  "Platformer",
  "Point & Click",
  "Puzzle",
  "Rhythm",
  "Roguelike",
  "RTS",
  "Sandbox",
  "Shooter",
  "Space Sim",
  "Strategy RPG",
  "Tabletop",
  "Tower Defense",
  "Trivia",
  "Turn-Based Strategy",
  "Utilities",
  "Video Production",
  "Visual Novel",
  "Walking Simulator",
  "Web Publishing",
  "Word Game",
  "2D Platformer",
  "3D Platformer",
  "Action RTS",
  "Arena Shooter",
  "Boomer Shooter",
  "Bullet Hell",
  "Card Battler",
  "Choose Your Own Adventure",
  "Clicker",
  "Collectathon",
  "Combat Racing",
  "Creature Collector",
  "Cricket",
  "CRPG",
  "Dungeon Crawler",
  "Exploration",
  "Flight",
  "FPS",
  "Hack and Slash",
  "Hero Shooter",
  "Hidden Object",
  "Idler",
  "Immersive Sim",
  "Looter Shooter",
  "Mahjong",
  "Match 3",
  "Medical Sim",
  "Metroidvania",
  "Mystery Dungeon",
  "On-Rails Shooter",
  "Outbreak Sim",
  "Political Sim",
  "Precision Platformer",
  "Puzzle Platformer",
  "Real Time Tactics",
  "Roguelite",
  "Roguevania",
  "Runner",
  "Shoot 'Em Up",
  "Shop Keeper",
  "Side Scroller",
  "Sokoban",
  "Solitaire",
  "Souls-like",
  "Spectacle fighter",
  "Spelling",
  "Tactical RPG",
  "Third-Person Shooter",
  "Time Management",
  "Top-Down Shooter",
  "Trading Card Game",
  "Traditional Roguelike",
  "Turn-Based Tactics",
  "Twin Stick Shooter",
  "Typing",
  "Wargame",
  "3D",
  "Stylized",
  "2.5D",
  "2D",
  "360 Video",
  "3D Vision",
  "Abstract",
  "Anime",
  "Cartoon",
  "Cartoony",
  "Cinematic",
  "Colorful",
  "Comic Book",
  "Cute",
  "First-Person",
  "FMV",
  "Hand-drawn",
  "Isometric",
  "Minimalist",
  "Noir",
  "Pixel Graphics",
  "Psychedelic",
  "Realistic",
  "Split Screen",
  "Text-Based",
  "Third Person",
  "Top-Down",
  "Voxel",
  "VR",
  "Comedy",
  "Dark Comedy",
  "Dark Humor",
  "Funny",
  "Management",
  "Satire",
  "1980s",
  "1990's",
  "Agriculture",
  "Aliens",
  "Alternate History",
  "America",
  "Archery",
  "Artificial Intelligence",
  "Assassin",
  "Atmospheric",
  "ATV",
  "Automation",
  "Baseball",
  "Basketball",
  "Bikes",
  "BMX",
  "Bowling",
  "Boxing",
  "Building",
  "Capitalism",
  "Cats",
  "Cold War",
  "Conspiracy",
  "Cooking",
  "Crafting",
  "Crime",
  "Cyberpunk",
  "Cycling",
  "Dark",
  "Dark Fantasy",
  "Demons",
  "Destruction",
  "Detective",
  "Dinosaurs",
  "Diplomacy",
  "Dog",
  "Dragons",
  "Drama",
  "Driving",
  "Dwarf",
  "Dystopian",
  "Economy",
  "Elf",
  "Emotional",
  "Faith",
  "Family Friendly",
  "Fantasy",
  "Fishing",
  "Football (American)",
  "Football (Soccer)",
  "Foreign",
  "Futuristic",
  "Gambling",
  "Game Development",
  "Golf",
  "Gothic",
  "Hacking",
  "Heist",
  "Historical",
  "Hockey",
  "Horror",
  "Horses",
  "Hunting",
  "Illuminati",
  "Investigation",
  "Jet",
  "LEGO",
  "Lemmings",
  "LGBTQ+",
  "Logic",
  "Loot",
  "Lore-Rich",
  "Lovecraftian",
  "Magic",
  "Mars",
  "Martial Arts",
  "Mechs",
  "Medieval",
  "Memes",
  "Military",
  "Mini Golf",
  "Mining",
  "Modern",
  "Motocross",
  "Motorbike",
  "Mystery",
  "Mythology",
  "Nature",
  "Naval",
  "Ninja",
  "Offroad",
  "Old School",
  "Otome",
  "Parkour",
  "Parody",
  "Philosophical",
  "Pirates",
  "Political",
  "Politics",
  "Pool",
  "Post-apocalyptic",
  "Programming",
  "Psychological",
  "Psychological Horror",
  "Relaxing",
  "Retro",
  "Robots",
  "Romance",
  "Rome",
  "Sailing",
  "Sci-fi",
  "Science",
  "Skateboarding",
  "Skating",
  "Skiing",
  "Sniper",
  "Snow",
  "Snowboarding",
  "Space",
  "Stealth",
  "Steampunk",
  "Submarine",
  "Superhero",
  "Supernatural",
  "Surreal",
  "Survival",
  "Survival Horror",
  "Swordplay",
  "Tactical",
  "Tanks",
  "Tennis",
  "Thriller",
  "Time Travel",
  "Trains",
  "Transhumanism",
  "Transportation",
  "Underground",
  "Underwater",
  "Vampire",
  "Vikings",
  "War",
  "Warhammer 40K",
  "Werewolves",
  "Western",
  "World War I",
  "World War II",
  "Wrestling",
  "Zombies",
  "Choices Matter",
  "Multiple Endings",
  "Story Rich",
  "6DOF",
  "Asymmetric VR",
  "Base Building",
  "Bullet Time",
  "Character Customization",
  "Class-Based",
  "Combat",
  "Controller",
  "Conversation",
  "Deckbuilding",
  "Dynamic Narration",
  "Female Protagonist",
  "Grid-Based Movement",
  "Gun Customization",
  "Hex Grid",
  "Inventory Management",
  "Level Editor",
  "Linear",
  "Moddable",
  "Music-Based Procedural Generation",
  "Narration",
  "Naval Combat",
  "Nonlinear",
  "Open World",
  "Perma Death",
  "Physics",
  "Procedural Generation",
  "PvE",
  "PvP",
  "Quick-Time Events",
  "Resource Management",
  "Score Attack",
  "Team-Based",
  "Time Manipulation",
  "Trading",
  "Turn-Based Combat",
  "Tutorial",
  "Vehicular Combat",
  "Singleplayer",
  "4 Player Local",
  "Asynchronous Multiplayer",
  "Co-op",
  "Co-op Campaign",
  "Local Co-Op",
  "Local Multiplayer",
  "Massively Multiplayer",
  "Multiplayer",
  "Online Co-op",
] as const;

export type SteamTag = (typeof STEAM_TAGS)[number];

export const STEAM_TAG_NAME_SET = new Set<string>(STEAM_TAGS);

const STEAM_TAG_NAME_MAP = new Map<string, SteamTag>(STEAM_TAGS.map((tag) => [tag.toLowerCase(), tag]));

export function filterCanonicalSteamTags(value: unknown): SteamTag[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const seen = new Set<SteamTag>();
  const result: SteamTag[] = [];

  for (const item of value) {
    if (typeof item !== "string") {
      continue;
    }

    const canonicalTag = STEAM_TAG_NAME_MAP.get(item.trim().toLowerCase());

    if (!canonicalTag || seen.has(canonicalTag)) {
      continue;
    }

    seen.add(canonicalTag);
    result.push(canonicalTag);
  }

  return result;
}